schema_version = "1.0.0"

id = "node_to_python"
version = "3.2.1"
name = "Node To Python"
tagline = "Turn node groups into Python code"
maintainer = "Brendan Parmer <brendanparmer+nodetopython@gmail.com>"
type = "add-on"

website = "https://github.com/BrendanParmer/NodeToPython"

tags = ["Development", "Compositing", "Geometry Nodes", "Material", "Node"]

blender_version_min = "4.2.0"
blender_version_max = "4.3.0"

license = [
    "SPDX:MIT",
]

[permissions]
files = "Creates and writes to files in a specified directory"